# Generated by Django 5.1 on 2024-09-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0002_alter_banner_description_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Banners'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='banner',
            name='position',
            field=models.TextField(choices=[(0, 'Esquerda'), (1, 'Direita'), (2, 'Centro'), (3, 'Ambos')], default=0, verbose_name='Posição'),
        ),
    ]
