# Generated by Django 5.1 on 2024-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0003_alter_banner_options_alter_sector_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='position',
        ),
        migrations.AddField(
            model_name='banner',
            name='align',
            field=models.TextField(choices=[('flex-start', 'Início'), ('flex-end', 'Fim'), ('center', 'Centro'), ('baseline', 'Base'), ('stretch', 'Esticar')], default='flex-start', verbose_name='Alinhamento Vertical'),
        ),
        migrations.AddField(
            model_name='banner',
            name='justify',
            field=models.TextField(choices=[('flex-start', 'Início'), ('flex-end', 'Fim'), ('center', 'Centro'), ('space-between', 'Espaçamento entre'), ('space-around', 'Espaçamento ao redor'), ('space-evenly', 'Espaçamento igual')], default='flex-start', verbose_name='Alinhamento Horizontal'),
        ),
    ]
