# Generated by Django 5.1 on 2024-09-28 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0005_banner_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='padding',
            field=models.IntegerField(default=0, verbose_name='Espaçamento interno (px)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='align',
            field=models.TextField(choices=[('flex-start', 'Início'), ('flex-end', 'Fim'), ('center', 'Centro'), ('baseline', 'Base'), ('stretch', 'Esticar')], default='flex-start', verbose_name='Posicionamento'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='justify',
            field=models.TextField(choices=[('flex-start', 'Início'), ('flex-end', 'Fim'), ('center', 'Centro'), ('space-between', 'Espaçamento entre'), ('space-around', 'Espaçamento ao redor'), ('space-evenly', 'Espaçamento igual')], default='flex-start', verbose_name='Alinhamento'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='width',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Largura (%)'),
        ),
    ]
