# Generated by Django 5.1 on 2024-09-28 18:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0006_banner_padding_alter_banner_align_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='padding',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)], verbose_name='Espaçamento interno (%)'),
        ),
    ]
