# Generated by Django 5.1 on 2024-09-28 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0007_alter_banner_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='size_description',
            field=models.IntegerField(default=150, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tamanho da descrição'),
        ),
        migrations.AddField(
            model_name='banner',
            name='size_title',
            field=models.IntegerField(default=350, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tamanho do titulo'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='align',
            field=models.TextField(choices=[('flex-start', 'Início'), ('flex-end', 'Fim'), ('center', 'Centro')], default='flex-start', verbose_name='Posicionamento horizontal'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='justify',
            field=models.TextField(choices=[('flex-start', 'Início'), ('flex-end', 'Fim'), ('center', 'Centro'), ('space-between', 'Espaçamento entre'), ('space-around', 'Espaçamento ao redor'), ('space-evenly', 'Espaçamento igual')], default='flex-start', verbose_name='Alinhamento vertical'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='padding',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Espaçamento interno (%)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='width',
            field=models.IntegerField(default=90, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)], verbose_name='Largura do texto (%)'),
        ),
    ]
