# Generated by Django 5.1 on 2024-09-28 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sector', '0009_alter_banner_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='size_description',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tamanho da descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='size_title',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tamanho do titulo'),
        ),
    ]
